config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"


  get 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  get 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_destroy"

  

  resources :products
  resources :orders
  resources :carts
  resources :admins
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, dependent: :destroy
  	has_many :products, through: :line_items

  	belongs_to :user, optional: true

  	# LOGIC
  	def sub_total
    	sum = 0
    	self.line_items.each do |line_item|
      		sum+= line_item.total_price
    	end
    	return sum
  	end
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_PAY_METHOD = ['cash on delivery', 'debit card', 'credit card', 'PhonePe/Paytm/GooglePay']

  included do
    validates :pay_method, inclusion: { in: VALID_PAY_METHOD }
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :product
  	belongs_to :cart
  	belongs_to :order, optional: true

  	attribute :quantity, :integer, :default => 0 

  	# LOGIC
  	def total_price
    	self.quantity * self.product.price
  	end
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :line_items, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :line_items, dependent: :destroy
	has_one_attached :image

	def image_url
		if self.image.attached?
			self.image
		else
			"https://cdn5.vectorstock.com/i/1000x1000/05/74/cream-or-gel-bottle-empty-cosmetic-product-vector-12660574.jpg"
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
		@products = Product.all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
 	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception

  	before_action :current_cart

  	private

  	def current_cart
  		if session[:cart_id]
    		cart = Cart.find_by(:id => session[:cart_id])
    		if cart.present?
      		@current_cart = cart
    		else
      		session[:cart_id] = nil
    		end
  		end

  		if session[:cart_id] == nil
    		@current_cart = Cart.create
    		session[:cart_id] = @current_cart.id
  		end

  		give_cart_to_real_user if @current_cart&.user_id.blank? && current_user.present? ## from guest user to real user only for starting phase one time

  		if current_user.present? && current_user.cart.present? && session[:cart_id].present?
  			current_user.cart.line_items << @current_cart.line_items
				@current_cart = current_user.cart
				session[:cart_id] = @current_cart.id
  		end
  	end

  	def give_cart_to_real_user
  		@current_cart.update(user_id: current_user.id)
  	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

	def create
  		# Find associated product and current cart
  		chosen_product = Product.find(params[:product_id])
  		current_cart = @current_cart

  		# If cart already has this product then find the relevant line_item and iterate quantity otherwise create a new line_item for this product
  		if current_cart.products.include?(chosen_product)
    		# Find the line_item with the chosen_product
    		@line_item = current_cart.line_items.find_by(:product_id => chosen_product)
    		# Iterate the line_item's quantity by one
    		@line_item.quantity += 1
  		else
    		@line_item = LineItem.new
    		@line_item.cart = current_cart
    		@line_item.product = chosen_product
    		@line_item.quantity = 1
  		end

  		# Save and redirect to cart show path
  		@line_item.save
  		redirect_to cart_path(current_cart)
	end

  	def add_quantity
  		@line_item = @current_cart.line_items.find(params[:id])
  		@line_item.quantity += 1
  		@line_item.save
  		redirect_to cart_path(@current_cart)
	end

	def reduce_quantity
  		@line_item = LineItem.find(params[:id])
  		if @line_item.quantity > 1
    		@line_item.quantity -= 1
  		end
		@line_item.save
  		redirect_to cart_path(@current_cart)
	end

  	def destroy
  		@line_item = LineItem.find(params[:id])
  		@line_item.destroy
  		redirect_to cart_path(@current_cart)
	end

	private
	def line_item_params
		params.require(:line_item).permit(:quantity,:product_id, :cart_id)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
    def order_params
      params.require(:order).permit(:name, :email, :address, :pay_method)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
    
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/index.html.erb
<h1>Products :</h1>

<% @products.each do |product| %>
	<div>
		<%= image_tag product.image_url, style: "width: 100px; height: 100px" %>
	</div>
	<div>
		Name: <%= product.name%>
	</div>
	<div>
		Price: <%= number_to_currency(product.price, unit: "₹")%>
	</div>

	<p>
    	<%= link_to "Edit", edit_product_path(product) %>
    	<%= button_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
  	</p>
	
	<hr>

<% end %>

<%= link_to "New product", new_product_path %>

app/views/carts/show.html.erb
<div style="height: 100px; width: 100%; background-color: lightblue; display: flex; justify-content: flex-end; align-items: center; padding-right: 20px;">
  
    <button style="background-color: white; border: 1px solid #ccc; border-radius: 4px; padding: 10px 20px; font-size: 16px; cursor: pointer; transition: background-color 0.3s ease;">
      Total products: <%= @current_cart.line_items.count %>
    </button>
  
</div>

<div>
  <h2>Cart show</h2>
  <ul>
    <% @cart.line_items.each do |line_item| %>
      <li>
        Item: <%= line_item.product.name %> /
        Price: <%= number_to_currency(line_item.product.price, unit: "₹") %> /
        Quantity: <%= line_item.quantity %> /
        Total Price: <%= number_to_currency(line_item.total_price, unit: "₹") %>
        <ul>
          <li>
            <%= link_to "Add one", line_item_add_path(id: line_item), method: :get %> |
            <%= link_to "Reduce one", line_item_reduce_path(id: line_item), method: :get %>
          </li>
          <li>
            <%= button_to "Remove item", line_item_destroy_path(line_item), method: :delete, data: { confirm: "Are you sure?" } %>
          </li>
        </ul>
      </li>
      <hr>
    <% end %>
  </ul>
  <h3>Sub total: <%= number_to_currency(@cart.sub_total, unit: "₹") %></h3>
</div>

<h2><%= link_to "Proceed to checkout", new_order_path %></h2>
<%= link_to "Empty cart", cart_path(@current_cart), method: :delete, data: { confirm: "Are you sure?"}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<h2>All Orders</h2>

<% @orders.each do |order| %>
  <p>Name: <%= order.name %></p>
  <p>Email: <%= order.email %></p>
  <p>Line Items: </p>
  <ul>
    <% order.line_items.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
  </ul>
<% end

app/views/orders/new.html.erb
<%= form_for(@order) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  <p>
    <%= f.label :pay_method %><br>
    <%= f.select :pay_method, Visible::VALID_PAY_METHOD %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Enter product name" %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, required: true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<div style="height: 100px; width: 100%; background-color: lightblue; display: flex; justify-content: flex-end; align-items: center; padding-right: 20px;">
  <a href=<%= "/carts/#{@current_cart.id}" %> style="text-decoration: none;">
    <button style="background-color: white; border: 1px solid #ccc; border-radius: 4px; padding: 10px 20px; font-size: 16px; cursor: pointer; transition: background-color 0.3s ease;">
      Go to Cart
    </button>
  </a>
</div>

<% if user_signed_in? %>
  <h1>Welcome Home, <%= current_user.email %></h1>
  <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <h1>Home</h1>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>


<%# <h2 style="text-align: center;">Products list</h2> %>
<h2>Product List</h2>
<% @products.each do |product| %>

  <div>
    <a href="/products/<%= product.id%>">
      <%= image_tag product.image_url, style: "width: 100px; height: 100px" %>
    </a>
  </div>

  <div>
  	<a href="/products/<%= product.id%>">
      Name : <%= product.name %>
    </a>
  </div>

  <div>
  	Price : <%= number_to_currency(product.price, unit: "₹")%>
  </div>
  <p>
    <%= button_to "Add #{product.name} to cart", line_items_path(:product_id => product.id) %>
  </p>
  <hr>
<% end%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1>Product</h1>

<div>
	<% if @product.image.attached? %>
  		<%= image_tag url_for(@product.image) %>
	<% else %>
  		<p>No image available</p>
	<% end %>
</div>
<div>
	Name : <%= @product.name %>
</div>
<div>
	Price : <%= @product.price %>
</div>